# Autogenerated wrapper script for faust_jll for x86_64-linux-gnu-cxx11
export faust, faust2alqt, faust2alsa, faust2alsaconsole, faust2android, faust2androidunity, faust2api, faust2atomsnippets, faust2au, faust2bela, faust2caqt, faust2caqtios, faust2csound, faust2csvplot, faust2dplug, faust2dssi, faust2dummy, faust2dummymem, faust2eps, faust2esp32, faust2faustvst, faust2firefox, faust2gen, faust2graph, faust2graphviewer, faust2ios, faust2jack, faust2jackconsole, faust2jackrust, faust2jackserver, faust2jaqt, faust2jaqtchain, faust2juce, faust2ladspa, faust2linuxunity, faust2lv2, faust2mathdoc, faust2mathviewer, faust2max6, faust2md, faust2msp, faust2netjackconsole, faust2netjackqt, faust2nodejs, faust2octave, faust2osxiosunity, faust2owl, faust2paqt, faust2pdf, faust2plot, faust2png, faust2portaudiorust, faust2pure, faust2puredata, faust2raqt, faust2ros, faust2rosgtk, faust2rpialsaconsole, faust2rpinetjackconsole, faust2sam, faust2sc, faust2sig, faust2sigviewer, faust2smartkeyb, faust2sndfile, faust2soul, faust2supercollider, faust2svg, faust2svgviewer, faust2teensy, faust2unity, faust2vcvrack, faust2vst, faust2vsti, faust2w32max6, faust2w32msp, faust2w32puredata, faust2w32vst, faust2w64max6, faust2w64vst, faust2wasm, faust2webaudiowasm, faust2webaudiowast, faust2winunity, faustoptflags, libHTTPDFaust, libOSCFaust, libfaust, stdfaust_lib, usage_sh

using LLVM_jll
using Ncurses_jll
using Zlib_jll
using libmicrohttpd_jll
using libsndfile_jll
JLLWrappers.@generate_wrapper_header("faust")
JLLWrappers.@declare_executable_product(faust)
JLLWrappers.@declare_file_product(faust2alqt)
JLLWrappers.@declare_file_product(faust2alsa)
JLLWrappers.@declare_file_product(faust2alsaconsole)
JLLWrappers.@declare_file_product(faust2android)
JLLWrappers.@declare_file_product(faust2androidunity)
JLLWrappers.@declare_file_product(faust2api)
JLLWrappers.@declare_file_product(faust2atomsnippets)
JLLWrappers.@declare_file_product(faust2au)
JLLWrappers.@declare_file_product(faust2bela)
JLLWrappers.@declare_file_product(faust2caqt)
JLLWrappers.@declare_file_product(faust2caqtios)
JLLWrappers.@declare_file_product(faust2csound)
JLLWrappers.@declare_file_product(faust2csvplot)
JLLWrappers.@declare_file_product(faust2dplug)
JLLWrappers.@declare_file_product(faust2dssi)
JLLWrappers.@declare_file_product(faust2dummy)
JLLWrappers.@declare_file_product(faust2dummymem)
JLLWrappers.@declare_file_product(faust2eps)
JLLWrappers.@declare_file_product(faust2esp32)
JLLWrappers.@declare_file_product(faust2faustvst)
JLLWrappers.@declare_file_product(faust2firefox)
JLLWrappers.@declare_file_product(faust2gen)
JLLWrappers.@declare_file_product(faust2graph)
JLLWrappers.@declare_file_product(faust2graphviewer)
JLLWrappers.@declare_file_product(faust2ios)
JLLWrappers.@declare_file_product(faust2jack)
JLLWrappers.@declare_file_product(faust2jackconsole)
JLLWrappers.@declare_file_product(faust2jackrust)
JLLWrappers.@declare_file_product(faust2jackserver)
JLLWrappers.@declare_file_product(faust2jaqt)
JLLWrappers.@declare_file_product(faust2jaqtchain)
JLLWrappers.@declare_file_product(faust2juce)
JLLWrappers.@declare_file_product(faust2ladspa)
JLLWrappers.@declare_file_product(faust2linuxunity)
JLLWrappers.@declare_file_product(faust2lv2)
JLLWrappers.@declare_file_product(faust2mathdoc)
JLLWrappers.@declare_file_product(faust2mathviewer)
JLLWrappers.@declare_file_product(faust2max6)
JLLWrappers.@declare_file_product(faust2md)
JLLWrappers.@declare_file_product(faust2msp)
JLLWrappers.@declare_file_product(faust2netjackconsole)
JLLWrappers.@declare_file_product(faust2netjackqt)
JLLWrappers.@declare_file_product(faust2nodejs)
JLLWrappers.@declare_file_product(faust2octave)
JLLWrappers.@declare_file_product(faust2osxiosunity)
JLLWrappers.@declare_file_product(faust2owl)
JLLWrappers.@declare_file_product(faust2paqt)
JLLWrappers.@declare_file_product(faust2pdf)
JLLWrappers.@declare_file_product(faust2plot)
JLLWrappers.@declare_file_product(faust2png)
JLLWrappers.@declare_file_product(faust2portaudiorust)
JLLWrappers.@declare_file_product(faust2pure)
JLLWrappers.@declare_file_product(faust2puredata)
JLLWrappers.@declare_file_product(faust2raqt)
JLLWrappers.@declare_file_product(faust2ros)
JLLWrappers.@declare_file_product(faust2rosgtk)
JLLWrappers.@declare_file_product(faust2rpialsaconsole)
JLLWrappers.@declare_file_product(faust2rpinetjackconsole)
JLLWrappers.@declare_file_product(faust2sam)
JLLWrappers.@declare_file_product(faust2sc)
JLLWrappers.@declare_file_product(faust2sig)
JLLWrappers.@declare_file_product(faust2sigviewer)
JLLWrappers.@declare_file_product(faust2smartkeyb)
JLLWrappers.@declare_file_product(faust2sndfile)
JLLWrappers.@declare_file_product(faust2soul)
JLLWrappers.@declare_file_product(faust2supercollider)
JLLWrappers.@declare_file_product(faust2svg)
JLLWrappers.@declare_file_product(faust2svgviewer)
JLLWrappers.@declare_file_product(faust2teensy)
JLLWrappers.@declare_file_product(faust2unity)
JLLWrappers.@declare_file_product(faust2vcvrack)
JLLWrappers.@declare_file_product(faust2vst)
JLLWrappers.@declare_file_product(faust2vsti)
JLLWrappers.@declare_file_product(faust2w32max6)
JLLWrappers.@declare_file_product(faust2w32msp)
JLLWrappers.@declare_file_product(faust2w32puredata)
JLLWrappers.@declare_file_product(faust2w32vst)
JLLWrappers.@declare_file_product(faust2w64max6)
JLLWrappers.@declare_file_product(faust2w64vst)
JLLWrappers.@declare_file_product(faust2wasm)
JLLWrappers.@declare_file_product(faust2webaudiowasm)
JLLWrappers.@declare_file_product(faust2webaudiowast)
JLLWrappers.@declare_file_product(faust2winunity)
JLLWrappers.@declare_file_product(faustoptflags)
JLLWrappers.@declare_library_product(libHTTPDFaust, "libHTTPDFaust.so.0")
JLLWrappers.@declare_library_product(libOSCFaust, "libOSCFaust.so.1")
JLLWrappers.@declare_library_product(libfaust, "libfaust.so.2")
JLLWrappers.@declare_file_product(stdfaust_lib)
JLLWrappers.@declare_file_product(usage_sh)
function __init__()
    JLLWrappers.@generate_init_header(LLVM_jll, Ncurses_jll, Zlib_jll, libmicrohttpd_jll, libsndfile_jll)
    JLLWrappers.@init_executable_product(
        faust,
        "bin/faust",
    )

    JLLWrappers.@init_file_product(
        faust2alqt,
        "bin/faust2alqt",
    )

    JLLWrappers.@init_file_product(
        faust2alsa,
        "bin/faust2alsa",
    )

    JLLWrappers.@init_file_product(
        faust2alsaconsole,
        "bin/faust2alsaconsole",
    )

    JLLWrappers.@init_file_product(
        faust2android,
        "bin/faust2android",
    )

    JLLWrappers.@init_file_product(
        faust2androidunity,
        "bin/faust2androidunity",
    )

    JLLWrappers.@init_file_product(
        faust2api,
        "bin/faust2api",
    )

    JLLWrappers.@init_file_product(
        faust2atomsnippets,
        "bin/faust2atomsnippets",
    )

    JLLWrappers.@init_file_product(
        faust2au,
        "bin/faust2au",
    )

    JLLWrappers.@init_file_product(
        faust2bela,
        "bin/faust2bela",
    )

    JLLWrappers.@init_file_product(
        faust2caqt,
        "bin/faust2caqt",
    )

    JLLWrappers.@init_file_product(
        faust2caqtios,
        "bin/faust2caqtios",
    )

    JLLWrappers.@init_file_product(
        faust2csound,
        "bin/faust2csound",
    )

    JLLWrappers.@init_file_product(
        faust2csvplot,
        "bin/faust2csvplot",
    )

    JLLWrappers.@init_file_product(
        faust2dplug,
        "bin/faust2dplug",
    )

    JLLWrappers.@init_file_product(
        faust2dssi,
        "bin/faust2dssi",
    )

    JLLWrappers.@init_file_product(
        faust2dummy,
        "bin/faust2dummy",
    )

    JLLWrappers.@init_file_product(
        faust2dummymem,
        "bin/faust2dummymem",
    )

    JLLWrappers.@init_file_product(
        faust2eps,
        "bin/faust2eps",
    )

    JLLWrappers.@init_file_product(
        faust2esp32,
        "bin/faust2esp32",
    )

    JLLWrappers.@init_file_product(
        faust2faustvst,
        "bin/faust2faustvst",
    )

    JLLWrappers.@init_file_product(
        faust2firefox,
        "bin/faust2firefox",
    )

    JLLWrappers.@init_file_product(
        faust2gen,
        "bin/faust2gen",
    )

    JLLWrappers.@init_file_product(
        faust2graph,
        "bin/faust2graph",
    )

    JLLWrappers.@init_file_product(
        faust2graphviewer,
        "bin/faust2graphviewer",
    )

    JLLWrappers.@init_file_product(
        faust2ios,
        "bin/faust2ios",
    )

    JLLWrappers.@init_file_product(
        faust2jack,
        "bin/faust2jack",
    )

    JLLWrappers.@init_file_product(
        faust2jackconsole,
        "bin/faust2jackconsole",
    )

    JLLWrappers.@init_file_product(
        faust2jackrust,
        "bin/faust2jackrust",
    )

    JLLWrappers.@init_file_product(
        faust2jackserver,
        "bin/faust2jackserver",
    )

    JLLWrappers.@init_file_product(
        faust2jaqt,
        "bin/faust2jaqt",
    )

    JLLWrappers.@init_file_product(
        faust2jaqtchain,
        "bin/faust2jaqtchain",
    )

    JLLWrappers.@init_file_product(
        faust2juce,
        "bin/faust2juce",
    )

    JLLWrappers.@init_file_product(
        faust2ladspa,
        "bin/faust2ladspa",
    )

    JLLWrappers.@init_file_product(
        faust2linuxunity,
        "bin/faust2linuxunity",
    )

    JLLWrappers.@init_file_product(
        faust2lv2,
        "bin/faust2lv2",
    )

    JLLWrappers.@init_file_product(
        faust2mathdoc,
        "bin/faust2mathdoc",
    )

    JLLWrappers.@init_file_product(
        faust2mathviewer,
        "bin/faust2mathviewer",
    )

    JLLWrappers.@init_file_product(
        faust2max6,
        "bin/faust2max6",
    )

    JLLWrappers.@init_file_product(
        faust2md,
        "bin/faust2md",
    )

    JLLWrappers.@init_file_product(
        faust2msp,
        "bin/faust2msp",
    )

    JLLWrappers.@init_file_product(
        faust2netjackconsole,
        "bin/faust2netjackconsole",
    )

    JLLWrappers.@init_file_product(
        faust2netjackqt,
        "bin/faust2netjackqt",
    )

    JLLWrappers.@init_file_product(
        faust2nodejs,
        "bin/faust2nodejs",
    )

    JLLWrappers.@init_file_product(
        faust2octave,
        "bin/faust2octave",
    )

    JLLWrappers.@init_file_product(
        faust2osxiosunity,
        "bin/faust2osxiosunity",
    )

    JLLWrappers.@init_file_product(
        faust2owl,
        "bin/faust2owl",
    )

    JLLWrappers.@init_file_product(
        faust2paqt,
        "bin/faust2paqt",
    )

    JLLWrappers.@init_file_product(
        faust2pdf,
        "bin/faust2pdf",
    )

    JLLWrappers.@init_file_product(
        faust2plot,
        "bin/faust2plot",
    )

    JLLWrappers.@init_file_product(
        faust2png,
        "bin/faust2png",
    )

    JLLWrappers.@init_file_product(
        faust2portaudiorust,
        "bin/faust2portaudiorust",
    )

    JLLWrappers.@init_file_product(
        faust2pure,
        "bin/faust2pure",
    )

    JLLWrappers.@init_file_product(
        faust2puredata,
        "bin/faust2puredata",
    )

    JLLWrappers.@init_file_product(
        faust2raqt,
        "bin/faust2raqt",
    )

    JLLWrappers.@init_file_product(
        faust2ros,
        "bin/faust2ros",
    )

    JLLWrappers.@init_file_product(
        faust2rosgtk,
        "bin/faust2rosgtk",
    )

    JLLWrappers.@init_file_product(
        faust2rpialsaconsole,
        "bin/faust2rpialsaconsole",
    )

    JLLWrappers.@init_file_product(
        faust2rpinetjackconsole,
        "bin/faust2rpinetjackconsole",
    )

    JLLWrappers.@init_file_product(
        faust2sam,
        "bin/faust2sam",
    )

    JLLWrappers.@init_file_product(
        faust2sc,
        "bin/faust2sc",
    )

    JLLWrappers.@init_file_product(
        faust2sig,
        "bin/faust2sig",
    )

    JLLWrappers.@init_file_product(
        faust2sigviewer,
        "bin/faust2sigviewer",
    )

    JLLWrappers.@init_file_product(
        faust2smartkeyb,
        "bin/faust2smartkeyb",
    )

    JLLWrappers.@init_file_product(
        faust2sndfile,
        "bin/faust2sndfile",
    )

    JLLWrappers.@init_file_product(
        faust2soul,
        "bin/faust2soul",
    )

    JLLWrappers.@init_file_product(
        faust2supercollider,
        "bin/faust2supercollider",
    )

    JLLWrappers.@init_file_product(
        faust2svg,
        "bin/faust2svg",
    )

    JLLWrappers.@init_file_product(
        faust2svgviewer,
        "bin/faust2svgviewer",
    )

    JLLWrappers.@init_file_product(
        faust2teensy,
        "bin/faust2teensy",
    )

    JLLWrappers.@init_file_product(
        faust2unity,
        "bin/faust2unity",
    )

    JLLWrappers.@init_file_product(
        faust2vcvrack,
        "bin/faust2vcvrack",
    )

    JLLWrappers.@init_file_product(
        faust2vst,
        "bin/faust2vst",
    )

    JLLWrappers.@init_file_product(
        faust2vsti,
        "bin/faust2vsti",
    )

    JLLWrappers.@init_file_product(
        faust2w32max6,
        "bin/faust2w32max6",
    )

    JLLWrappers.@init_file_product(
        faust2w32msp,
        "bin/faust2w32msp",
    )

    JLLWrappers.@init_file_product(
        faust2w32puredata,
        "bin/faust2w32puredata",
    )

    JLLWrappers.@init_file_product(
        faust2w32vst,
        "bin/faust2w32vst",
    )

    JLLWrappers.@init_file_product(
        faust2w64max6,
        "bin/faust2w64max6",
    )

    JLLWrappers.@init_file_product(
        faust2w64vst,
        "bin/faust2w64vst",
    )

    JLLWrappers.@init_file_product(
        faust2wasm,
        "bin/faust2wasm",
    )

    JLLWrappers.@init_file_product(
        faust2webaudiowasm,
        "bin/faust2webaudiowasm",
    )

    JLLWrappers.@init_file_product(
        faust2webaudiowast,
        "bin/faust2webaudiowast",
    )

    JLLWrappers.@init_file_product(
        faust2winunity,
        "bin/faust2winunity",
    )

    JLLWrappers.@init_file_product(
        faustoptflags,
        "bin/faustoptflags",
    )

    JLLWrappers.@init_library_product(
        libHTTPDFaust,
        "lib/libHTTPDFaust.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libOSCFaust,
        "lib/libOSCFaust.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libfaust,
        "lib/libfaust.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_file_product(
        stdfaust_lib,
        "share/faust/stdfaust.lib",
    )

    JLLWrappers.@init_file_product(
        usage_sh,
        "bin/usage.sh",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
